/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;
    import Frame.formmenuadmin;
    import java.awt.print.PrinterException;
    import java.sql.Connection;
    import java.sql.DriverManager;
    import java.sql.PreparedStatement;
    import java.sql.SQLException;
    import javax.swing.JOptionPane;
    import java.sql.Statement;
/**
 *
 * @author ACER
 */
public class caridata extends javax.swing.JFrame {
    Connection connect =null;
    Statement state = null;
    String user="root";
    String pswd ="";
    String host="localhost";
    String db="DbDataSI";
    String url="";

    /**
     * Creates new form caridata
     */
    public caridata() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNIK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtnama = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtjenis = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txttmpt = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txttanggal = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtagama = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtpendidikan = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtpekerjaan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(txtNIK);
        txtNIK.setBounds(210, 30, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Silahkan masukkan NIK :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 20, 150, 40);

        txtcari.setText("Cari");
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        jPanel1.add(txtcari);
        txtcari.setBounds(370, 30, 51, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/keluar.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(460, 10, 30, 30);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 70);

        jPanel3.setLayout(new java.awt.GridLayout(10, 2, 8, 8));

        jLabel7.setText("NAMA :");
        jPanel3.add(jLabel7);
        jPanel3.add(txtnama);

        jLabel11.setText("Jenis Kelamin :");
        jPanel3.add(jLabel11);
        jPanel3.add(txtjenis);

        jLabel13.setText("Tempat Lahir :");
        jPanel3.add(jLabel13);
        jPanel3.add(txttmpt);

        jLabel12.setText("Tanggal Lahir :");
        jPanel3.add(jLabel12);
        jPanel3.add(txttanggal);

        jLabel17.setText("Agama  :");
        jPanel3.add(jLabel17);
        jPanel3.add(txtagama);

        jLabel20.setText("Pendidikan  :");
        jPanel3.add(jLabel20);
        jPanel3.add(txtpendidikan);

        jLabel19.setText("Pekerjaan   :");
        jPanel3.add(jLabel19);
        jPanel3.add(txtpekerjaan);

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 70, 500, 200);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 10, 30, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void layarawal(){
        txtNIK.setText("");
    }
    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        if (txtNIK.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Harap Masukkan NIK!");
            txtNIK.requestFocus();
        }else{
            try{
                String sql = "SELECT  * FROM data  WHERE "+ "NIK ='" + txtNIK.getText() + "'";
                connect = DriverManager.getConnection("jdbc:mysql://localhost/datapenduduk","root","");
                java.sql.Statement state = connect.createStatement();
                java.sql.ResultSet rs = state.executeQuery(sql);
                
                if (rs.next()) {
                    txtnama.setText(rs.getString("Nama")) ;
                    txtjenis.setText(rs.getString("Jenis Kelamin")) ;
                    txttmpt.setText(rs.getString("Tempat Lahir")) ;
                    txttanggal.setText(rs.getString("Tanggal Lahir")) ;
                    txtagama.setText(rs.getString("Agama")) ;
                    txtpendidikan.setText(rs.getString("Pendidikan")) ;
                    txtpekerjaan.setText(rs.getString("Pekerjaan")) ;
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Nomor Pesanan tidak ditemukan!");
                    txtNIK.setText("");
                }
            }catch(SQLException e){
            }
        }
    }//GEN-LAST:event_txtcariActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new formmenuadmin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            txtnama.setText("") ;
            txtjenis.setText("") ;
            txttmpt.setText("") ;
            txttanggal.setText("") ;
            txtagama.setText("") ;
            txtpendidikan.setText("") ;
            txtpekerjaan.setText("") ;
    }//GEN-LAST:event_jButton3ActionPerformed
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caridata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caridata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caridata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caridata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caridata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JLabel txtagama;
    private javax.swing.JButton txtcari;
    private javax.swing.JLabel txtjenis;
    private javax.swing.JLabel txtnama;
    private javax.swing.JLabel txtpekerjaan;
    private javax.swing.JLabel txtpendidikan;
    private javax.swing.JLabel txttanggal;
    private javax.swing.JLabel txttmpt;
    // End of variables declaration//GEN-END:variables
}
